### ISSUE TITLE
Gets stuck on error

### ISSUE THREAD

**Issue by yanNotDev** [HaiDang666/extract-sptf-playlist#4]
Code:
```js
const { getSpotifyPlaylist} = require('extract-sptf-playlist');
const url = 'https://open.spotify.com/playlist/2YCIIABnzPtI9cuXn0y9bb';
getSpotifyPlaylist(url, { filePath: 'a.json' });
````
Output:
```
C:\Users\aayan\Downloads\playlist\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:218
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read property 'getAttribute' of null
    at __puppeteer_evaluation_script__:15:11
    at ExecutionContext._evaluateInternal (C:\Users\aayan\Downloads\playlist\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:218:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\aayan\Downloads\playlist\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)    at async getTracksFromDOM (C:\Users\aayan\Downloads\playlist\node_modules\extract-sptf-playlist\spotify.js:55:21)
    at async getData (C:\Users\aayan\Downloads\playlist\node_modules\extract-sptf-playlist\spotify.js:120:23)
```

**Comment by haidang666** [comment]
Thank you, it's fixed in v1.0.1
