### ISSUE TITLE
How am I supposed to use this?

### ISSUE THREAD

**Issue by ShawkMusic** [HaiDang666/extract-sptf-playlist#5]
I'm here from https://github.com/nukeop/nuclear/issues/978

I cloned this Github repository to my computer and I'm not entirely sure what to do to turn my Spotify playlists into a file I can import to Nuclear.
Am I supposed to run a file or something?
(I'm on Linux btw)

**Comment by haidang666** [comment]
After cloning this, open the [exampleSpotify.js](https://github.com/HaiDang666/extract-sptf-playlist/blob/master/exampleSpotify.js) file and replace the current URL with your playlist URL, save the change and execute with the command `node exampleSpotify.js`. FYI, this repo requires node 12+.

**Comment by ShawkMusic** [comment]
Now I'm getting this error:

```
~/Documents/git_clones/extract-sptf-playlist/spotify.js:70
            ?.getAttribute('src');
             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (~/Documents/git_clones/extract-sptf-playlist/index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

I'm on Node 12.22.8

**Comment by haidang666** [comment]
My mistake, can you switch to node 14+

**Comment by lostybtw** [comment]
#9
