### ISSUE TITLE
A Lot Of '?' and '.' randomly in the scripts

### ISSUE THREAD

**Issue by lostybtw** [HaiDang666/extract-sptf-playlist#8]
/home/lostancient/node_modules/extract-sptf-playlist/spotify.js:60
      if (nodeTracks?.[i]) {
                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lostancient/node_modules/extract-sptf-playlist/index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by lostybtw** [comment]
#9

**Comment by lostybtw** [comment]
I fixed it

**Comment by lostybtw** [comment]
Sorry, Realised I was on node-lts
